### ISSUE TITLE
Is it possible to configure it so that the "Insert new indented line after Return" action does not scroll the buffer?

### ISSUE THREAD

**Issue by unphased** [jiangmiao/auto-pairs#103]
First off i would like to applaud you for making this plugin, it has a lot of really in-depth features that allows so much customization of the helping behavior, and it finally brings bracket-pair Sublime Text feature parity to Vim and goes a bit further, too. :+1: 

I am not sure what causes this, it might be some weird interaction between plugins. But, what I experience is that when my cursor is near the bottom (I have to do it when the cursor is aruond about 60% from the top of the screen, or lower down), and I type 

    else {<CR>

the plugin helpfully completes the closing `}` on the line after the line just created, however this causes a ridiculously disorienting scrolling and warping of the cursor back to the middle of the screen. 

I find that line 364 in the code is responsible for this, and in fact the code is doing precisely a check to see if the cursor is inside the last one-third of the buffer area. So I think I will go ahead and fork and remove this feature myself and I wonder if you would like to expose this as a configurable option.

It's definitely exacerbated by the fact that I am using a screen and font size that displays 177 lines (I have a 2560 monitor in portrait and 9pt font). This would have my cursor yanked up a good 80+ lines if I so happen to add an else clause or function or pretty much anything near the bottom.

**Comment by jiangmiao** [comment]
`let AutoPairsCenterLine = 0` to disable center line feature.

**Comment by unphased** [comment]
I can't believe I missed that when I wrote my hack. Thanks!
