### ISSUE TITLE
建议：在可能是注释的情况下，不要闭合引号

### ISSUE THREAD

**Issue by tolinwei** [jiangmiao/auto-pairs#108]
不确定这样子是否是普遍场景，但是我经常遇到，比如说下面的vimrc设置，当我要在一行的后面添加注释的时候，引号还是会自动闭合
```
set number                                             " Show line number
syntax on                                              " Open syntax highlighting
```
我知道现有的功能是，在行首输入一个引号的话，不会自动闭合（因为有很大的可能那个是注释）。如果能够添加一种不会自动闭合的情况给上面的情景，会更棒，既：在输入引号的时候，如果引号前面有多于一个空格或者多于一个tab。
不知道能否实现这样子的功能。

**Comment by hanjianwei** [comment]
How do you handle the following case:

~~~ vim
let foo = "hello"
~~~

I think you can use [nerdcommenter](https://github.com/scrooloose/nerdcommenter) and press `<Leader>cA` if you want to append a comment string to current line.
