### ISSUE TITLE
How to turn off auto pair function when I edit a special file. Such as .smali

### ISSUE THREAD

**Issue by huhuang03** [jiangmiao/auto-pairs#109]
Could any tell me how I can set in .vimrc file to finish this.

**Comment by huhuang03** [comment]
Sorry, I just want to disable [] auto pair

**Comment by junkmechanic** [comment]
You can disable autopairs using the shortcut <M-p> (or if you have changed that. Please check the README for the function `g:AutoPairsShortcutToggle`

**Comment by cledoux** [comment]
Assuming filetypes are on and recognizing smali filetypes, place following in vimrc:

    au Filetype smali let b:AutoPairs={'(':')', '{':'}',"'":"'",'"':'"', '`':'`'}

I accomplished a similar thing for LaTex files. I needed the mapping on `"` and `'` disabled for some smart formatting I have to work.
