### ISSUE TITLE
Autocomplete HTML brackets

### ISSUE THREAD

**Issue by jviotti** [jiangmiao/auto-pairs#113]
I'm looking forward to autocomplete `<` with `>`.

I've attempted the following without success in my `vimrc` *after* AutoPairs is loaded:

```vimscript
let g:AutoPairs['<'] = '>'
```

***

```vimscript
call extend(g:AutoPairs, { '<': '>' })
```

What's the correct way of extending the provided dictionary?

**Comment by stonewareslord** [comment]
Based on: https://github.com/jiangmiao/auto-pairs/blob/master/plugin/auto-pairs.vim#L16

It looks like you can use:

```
let g:AutoPairs = {'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`', '<':'>'}
```

**Comment by jviotti** [comment]
@stonewareslord That worked fine! Thanks!
