### ISSUE TITLE
Jinja/Twig Autocompletion

### ISSUE THREAD

**Issue by stonewareslord** [jiangmiao/auto-pairs#114]
[Jinja](http://jinja.pocoo.org/)/[Twig](http://twig.sensiolabs.org/) syntax looks like this:

```
{% block body %}
{% endblock %}
```

This is the goal:

```
input: {
output: {|}

input: {%
output: {%|%}

input: {%<space>
output: {% | %}
```

And the actual result:

```
input: {
output: {|}

input: {%
output: {%|}

input: {%<space>
output: {% |}
```

I tried running:

```
let g:AutoPairs = {'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`', '<':'>', '{%':'%}'}
```

But this was the result:

```
input: {
output: {|}

input: {%
output: {%%|}

input: {%<space>
output: {%% |}
```

**Comment by brunoti** [comment]
Do you find a solution for that? I'm having the same trouble.

**Comment by stonewareslord** [comment]
No, unfortunately I haven’t fixed this. I’ve just been typing it in manually.

**Comment by stonewareslord** [comment]
Their syntax also includes comments, which also don’t work:

```
{# Twig comment #}
```

**Comment by bserem** [comment]
This would be a killer feature! Maybe we should auto-insert the spaces too!

I just found out about auto-pairs, due to my switch to twig. I'll dig a bit too.

**Comment by Svtter** [comment]
Maybe add a `['%':'%']` to `g:AutoPairs` is a good choice.

**Comment by stonewareslord** [comment]
The problem with that is that every time I try to use a % operator in another language, it will write %%

**Comment by Kasama** [comment]
I had the same problem, and implemented a solution for it. I have opened the pull request #219, but as the project seems a bit dead i doubt it's gonna be merged upstream anytime soon.

If anyone would like to, it's possible to use my fork to have this functionality

**Comment by Svtter** [comment]
I've found a way to solve this problem. Use snippets to create the pairs.

**Comment by jiangmiao** [comment]
AutoPairs supports multibyte pairs now.
```
au FileType php      let b:AutoPairs = AutoPairsDefine({'<?' : '?>', '<?php': '?>'})
```

**Comment by Svtter** [comment]
amazing work ~
