### ISSUE TITLE
 "C-h" becomes a backspace 

### ISSUE THREAD

**Issue by ghost** [jiangmiao/auto-pairs#119]
if I use "inoremap \<C-h\>  \<Left\>" in .vimrc, 
the 428 line makes "C-h" becomes a backspace 
428  execute 'inoremap \<buffer\> \<silent\> \<C-H\> \<C-R\>=AutoPairsDelete()\<CR\>'

**Comment by Delapouite** [comment]
You may find some clues there : https://github.com/neovim/neovim/issues/2048

**Comment by valerymercury** [comment]
Hi I have the same problem.
Did you find a workaround to fix that ?
