### ISSUE TITLE
Disable autopairs for certain filetypes

### ISSUE THREAD

**Issue by gaspaio** [jiangmiao/auto-pairs#128]
It would be nice to have an option to disable the autopairing behavior for certain filetypes.
use case : when i'm writing a markdown file I don't want autopairs to write '' everytime I write '.

Maybe this is already possible, in which case can somebody please explain to me how to do it ?
thanks.

**Comment by cledoux** [comment]
If you want to disable it entirely, you can place the following in vimrc.

    au Filetype markdown let b:autopairs_enabled = 0

This will have the same effect as the `<M-p>` shortcut that toggles autopairs.

If you only want to disable the `'` auto pair, you can overwrite the pairings and remove `'`:

    au Filetype markdown let b:AutoPairs={'(':')', '[':']', '{':'}','"':'"', '`':'`'}

These, of course, assume that filetype recognition is on and working correctly.

**Comment by gaspaio** [comment]
Thanks @cledoux.

**Comment by gaspaio** [comment]
``` au Filetype markdown let b:autopairs_enabled = 0 ``` doesn't seem to work. I put it in my vimrc, reloaded and autopairs is still active, and the file is correctly identified as markdown

**Comment by cledoux** [comment]
This should do it:

    au Filetype markdown let b:autopairs_loaded=1

Apologies, I apparently did a poor job of testing the last autocmd. Auto pairs defines it's own autocmd initialization function that overwrites `b:autopairs_enabled`. 

The initialization function is guarded by `b:autopairs_loaded` to ensure it only executes once. By setting it ourselves, the plugin is never initialized.

**Comment by gaspaio** [comment]
That works, thanks. I'm closing the issue.
