### ISSUE TITLE
New line behaviour breaks with vim-go after first save

### ISSUE THREAD

**Issue by achilleas-k** [jiangmiao/auto-pairs#149]
When paired with [vim-go](https://github.com/fatih/vim-go) the new line behaviour breaks after the first save. 
The intended behaviour:
```
input: {|} (press <CR> at |)
output: {
    |
}
```
works fine at first. Once the file is saved, the next time the same input is given, the behaviour changes to:
```
input: {|} (press <CR> at |)
output: {
|}
```

Disabling fmt on save (`let g:go_fmt_autosave = 0`) fixes this issue, but this is just a workaround.

**Comment by achilleas-k** [comment]
I've narrowed the issue down a bit. I am able to reproduce the issue by clearing my ~/.vim directory and ~/.vimrc file and simply installing SimpleAutoComplPop, vim-go, and auto-pairs.

**Comment by roxma** [comment]
This issue is fixed [here](https://github.com/roxma/SimpleAutoComplPop/issues/8).  It's a key mapping conflicts. I've remove it from sacp. NVM.

**Comment by achilleas-k** [comment]
Issue fixed in SACP. Closing.
