### ISSUE TITLE
support auto pairs for neocomplcache complete.

### ISSUE THREAD

**Issue by stardiviner** [jiangmiao/auto-pairs#16]
I'm using neocomplcache, neocomplcache complete function like this `aa.func(`, I hope auto pairs can work here.
I posted an issue at neocomplcache repo, someone told me, this should be implemented by autopairs.

**Comment by cseelus** [comment]
So the only real solution still is to disable auto-pairs neat `MapCR` functionality with `let g:AutoPairsMapCR = 0`?

**Comment by ysolis** [comment]
@cseelus maybe https://github.com/jiangmiao/auto-pairs/issues/116#issuecomment-141840018 can be your solution, I have something similar in https://github.com/jiangmiao/auto-pairs/issues/91#issuecomment-241692588 .
