### ISSUE TITLE
Why ShortcutJump is mapped in normal mode as well?

### ISSUE THREAD

**Issue by yevhen-m** [jiangmiao/auto-pairs#163]
Hey, I like your shortcutjump feature a lot. But why a key I choose for it is mapped in normal mode as well?
`let g:AutoPairsShortcutJump='<c-k>'`
Have you considered mapping this key only in insert mode? I want to use `<c-k>` in normal mode for another purpose, but, as it is right now, I can't.

**Comment by matthewgrossman** [comment]
@yevhen-m did you ever get resolution on this? I also don't want my mapping in normal mode

**Comment by yevhen-m** [comment]
@matthewgrossman  I guess you can fork and delete those `execute 'noremap'` calls.

**Comment by matthewgrossman** [comment]
I just extracted out the imap part and am doing am no longer using `g:AutoPairsShortcutJump`:

`inoremap <C-v> <C-o>:call AutoPairsJump()<CR>`

**Comment by matthewgrossman** [comment]
taken from https://github.com/jiangmiao/auto-pairs/blob/6afc850e2429e6832a1b093e32a31e0b5eff477d/plugin/auto-pairs.vim#L500
