### ISSUE TITLE
How to quick change bracket type?

### ISSUE THREAD

**Issue by NamPNQ** [jiangmiao/auto-pairs#165]
It's not issuse 
How to quick change bracket type
example:
input: [bla]
output: {bla}

**Comment by smiechowy** [comment]
It's not in scope of this plugin. Use https://github.com/tpope/vim-surround
Place cursor somewhere inside word and use: `cs]}` (change surround [from] ']' [to] '}').

**Comment by NamPNQ** [comment]
tkx @kborkows
