### ISSUE TITLE
AutoPairs cannot be fully deactivated for a filetype & conflicts with SLIMV

### ISSUE THREAD

**Issue by dkvasnicka** [jiangmiao/auto-pairs#179]
SLIMV is the most widely used Vim plugin for writing Lisp and Scheme and contains paredit to edit parens in lispy code.
AutoPairs has some similar features but overall is inferiof for lisps and so I don't want it activated.

I tried setting `b:AutoPairs` to an empty list for the appropriate filetypes but that doesn't turn AP off completely and it then still interferes with paredit, especially when deleting parens (paredit guarantees that your code will _never_ at any point in time contain unbalanced parens and AP breaks that).

I tried using `vim-plug` and load your plugin conditionally but that only works when editing lisps _only_. Once I open, say, a JS file in a new buffer in the same Vim instance AP activates and breaks editing in the lisp buffers that had been already open. Opening a JS file first and then a lisp one - same problem. The only way this can work is when I have two separate windows of MacVim.

Would it be possible to make it so that I can _fully_ deactivate AP for buffers with certain filetypes?

**Comment by jiangmiao** [comment]
A roughly solution is using `au FileType lisp let b:autopairs_loaded=1` to skip auto pairs initialization then it would be fully deactivated

**Comment by dkvasnicka** [comment]
Seems to do the trick, thanks!
