### ISSUE TITLE
Pressing Enter is broken in C/C++

### ISSUE THREAD

**Issue by kshenoy** [jiangmiao/auto-pairs#18]
Pressing enter in insert mode inserts the following text

```
<SNR>22_HandlePossibleSelectionEnter()
```

This problem is faced only when I use auto-pairs along with [clang-complete](git://github.com/Rip-Rip/clang_complete.git)

**Comment by grasshopyx** [comment]
我也遇到了类似的问题。在使用clang_complete的时候，按回车会返回
    <SNR>61_AutoPairsReturn
