### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by jamesdhooks** [jiangmiao/auto-pairs#184]
None of the keyboard shortcuts work for me. For example FastWrap is <M-e> i.e. alt-e. Does nothing. 
Tried remapping with `let g:AutoPairsShortcutFastWrap='<C-e>'` and also tried a bunch of other bindings. , nothing works, What might be the problem?

**Comment by James-A1** [comment]
Hi, I had the same problem. I found out my alt key wasn't firing at all inside vim. If you still want to use the alt key and are on a  vim GNOME version like me, I suggest taking a look at this:  [this](https://stackoverflow.com/questions/6778961/alt-key-shortcuts-not-working-on-gnome-terminal-with-vim)

Then you can try it out by going into insert mode, place the cursor right before a character or word, enter a wrapping character like ( or { and then execute the keybinding, which by default is `<M-e>`

**Comment by jamesdhooks** [comment]
Thank you! Seems to work now.  Much appreciated.
