### ISSUE TITLE
Bugged `<` (less than) in Neovim

### ISSUE THREAD

**Issue by reujab** [jiangmiao/auto-pairs#187]
In your script, there is a [for loop that creates meta keybindings](https://github.com/jiangmiao/auto-pairs/blob/f0019fc6423e7ce7bbd01d196a7e027077687fda/plugin/auto-pairs.vim#L461) in insert mode for all `AutoPairsMoveCharacter`s:
```viml
for key in split(b:AutoPairsMoveCharacter, '\s*')
  let escaped_key = substitute(key, "`'", "''", 'g')
  execute 'inoremap <silent> <buffer> <M-'.key."> <C-R>=AutoPairsMoveCharacter('".escaped_key."')<CR>"
endfor
```

This for loop tries to create a binding for <kbd>&lt;M-"></kbd>, but that's not a valid keybinding.

No meta keybindings seem to be set in Vim, but in Neovim, when you press <kbd>&lt;</kbd>, it waits `timeoutlen` amount of milliseconds before truly inserting the character because Neovim expects a literal <kbd>&lt;</kbd>, <kbd>M</kbd>, <kbd>-</kbd>, <kbd>"</kbd>, and <kbd>></kbd>.

<pre>
:imap

i  &lt;M-'>       *@&lt;C-R>=AutoPairsMoveCharacter('''')&lt;CR>
i  &lt;M-(>       *@&lt;C-R>=AutoPairsMoveCharacter('(')&lt;CR>
i  &lt;M-)>       *@&lt;C-R>=AutoPairsMoveCharacter(')')&lt;CR>
i  &lt;M-[>       *@&lt;C-R>=AutoPairsMoveCharacter('[')&lt;CR>
i  &lt;M-]>       *@&lt;C-R>=AutoPairsMoveCharacter(']')&lt;CR>
i  &lt;M-{>       *@&lt;C-R>=AutoPairsMoveCharacter('{')&lt;CR>
i  &lt;M-}>       *@&lt;C-R>=AutoPairsMoveCharacter('}')&lt;CR>
<b>i  &lt;M-">       *@&lt;C-R>=AutoPairsMoveCharacter('"')&lt;CR></b>
</pre>

In this screencast, you can see that the <kbd>&lt;M-"></kbd> binding is not grayed out like the others:
![screencast](https://user-images.githubusercontent.com/23725670/28546817-09bb5e0c-709a-11e7-9db0-b2e4ceb21c15.gif)

**Comment by mayesheng** [comment]
Any solution? I have exactly the same problem in nvim.

**Comment by reujab** [comment]
@mayesheng You can temporarily fix this issue by applying the following patch:
```diff
diff --git a/plugin/auto-pairs.vim b/plugin/auto-pairs.vim
index b2a9af7..d2dd3f7 100644
--- a/plugin/auto-pairs.vim
+++ b/plugin/auto-pairs.vim
@@ -459,6 +459,10 @@ function! AutoPairsInit()
   endfor
 
   for key in split(b:AutoPairsMoveCharacter, '\s*')
+    if key == '"'
+      continue
+    endif
+
     let escaped_key = substitute(key, "'", "''", 'g')
     execute 'inoremap <silent> <buffer> <M-'.key."> <C-R>=AutoPairsMoveCharacter('".escaped_key."')<CR>"
   endfor
```

I'm sure there's a better way to fix this, but since I don't know Vimscript too well, this is the best I could come up with.

**Comment by mayesheng** [comment]
@reujab Thank you! Your hack works!

**Comment by andreyorst** [comment]
Happens in my termux vim and neovim both

**Comment by ruipgpinheiro** [comment]
this seems to work, as a workaround that does not require patching auto-pairs:

    autocmd VimEnter,BufEnter,BufWinEnter * silent! iunmap <buffer> <M-">

Basically, try to unmap the bad mapping any time we switch to a buffer.

**Comment by tmilloff** [comment]
A workaround that seems to have no negative ill effects for me is the following line in my .vimrc
`  let g:AutoPairsMoveCharacter = ""`
This bypasses
`
if !exists('g:AutoPairsMoveCharacter')
  let g:AutoPairsMoveCharacter = "()[]{}\"'"
end
`
the value of which is later used in `
  if !exists('b:AutoPairsMoveCharacter')
    let b:AutoPairsMoveCharacter = g:AutoPairsMoveCharacter
  end
`
I don't use any of the M-Something mappings provided, but if you do, I assume you could set `let g:AutoPairsMoveCharacter = "()[]{}'"`. I haven't tested that however.

**Comment by valignatev** [comment]
Seems like it was fixed in the neovim. I don't see this issue anymore

https://github.com/neovim/neovim/issues/7410
