### ISSUE TITLE
Option to Change Default Spaceing of New Indented Line

### ISSUE THREAD

**Issue by vishalkr07** [jiangmiao/auto-pairs#189]
Add an option to change the default spacing of new indented line. If it exists, then add in the documentation.

**Comment by dylan-chong** [comment]
Just so where on the same page, could you give an example of what you are experiencing versus what you would want?

For me, i get this:

```
method(
|
      )

```
but i would rather have this:
```
method(
    |
)
```

**Comment by vishalkr07** [comment]
I am getting this. 8 space indentation.

        method(
                |
        )

And I want this. 4 space.

        method(
            |
        )

**Comment by vishalkr07** [comment]
This issues has nothing to do with the plugin. Changing the default value of shiftwidth, tabstop,  and softtabstop in .vimrc will fix this problem.
