### ISSUE TITLE
When exiting insert mode, do not remove tab

### ISSUE THREAD

**Issue by Hacksaurus** [jiangmiao/auto-pairs#191]
Hello!
I wanted know where I can edit your code so that whenever I add `{}` and then hit enter (Which then appropriately adds a tab), it does not remove that tab whenever I exit insert mode.
Here's an asciinema to demostrate:
https://asciinema.org/a/pFDUk4XDCaJNjwxeL85InNEFJ
Thanks for any help!

**Comment by reujab** [comment]
To not remove the indentation when pressing <kbd>Esc</kbd>, add this to your `.vimrc`:
```viml
inoremap <esc> ~<bs><esc>
```

To not remove the indentation when pressing <kbd>Enter</kbd>, add this to your `.vimrc`:
```viml
inoremap <cr> ~<bs><cr>
```

**Comment by Hacksaurus** [comment]
Thank you! The first suggestion is exactly what I needed!

Closing this thread!

**Comment by Hacksaurus** [comment]
Wait I also have another situation where that taps disappear...
Whenever I use the Up or Down arrow keys, the first tab disappears... how would I disable not removing the tabs @reujab ?

**Comment by reujab** [comment]
@Hacksaurus That's odd because
```viml
inoremap <up> ~<bs><up>
inoremap <down> ~<bs><down>
```
works when I try it.

What is the output of `:imap`?

**Comment by Hacksaurus** [comment]
This is the output of `imap` is this:
```
i  <BS>        *@<C-R>=AutoPairsDelete()<CR>
i  §           *@<C-R>=AutoPairsMoveCharacter('''')<CR>
i  ¢           *@<C-R>=AutoPairsMoveCharacter('"')<CR>
i  ©           *@<C-R>=AutoPairsMoveCharacter(')')<CR>
i  ¨           *@<C-R>=AutoPairsMoveCharacter('(')<CR>
i  î           *@<Esc>:call AutoPairsJump()<CR>a
i  ð           *@AutoPairsToggle()
i  â           *@<C-R>=AutoPairsBackInsert()<CR>
i  å           *@<C-R>=AutoPairsFastWrap()<CR>
i  ý           *@<C-R>=AutoPairsMoveCharacter('}')<CR>
i  û           *@<C-R>=AutoPairsMoveCharacter('{')<CR>
i  Ý           *@<C-R>=AutoPairsMoveCharacter(']')<CR>
i  Û           *@<C-R>=AutoPairsMoveCharacter('[')<CR>
i  <C-H>       *@<C-R>=AutoPairsDelete()<CR>
i  <CR>        &@~<BS><CR><SNR>50_AutoPairsReturn
i  <Space>     *@<C-]><C-R>=AutoPairsSpace()<CR>
i  "           *@<C-R>=AutoPairsInsert('"')<CR>
i  '           *@<C-R>=AutoPairsInsert('''')<CR>
i  (           *@<C-R>=AutoPairsInsert('(')<CR>
i  )           *@<C-R>=AutoPairsInsert(')')<CR>
i  [           *@<C-R>=AutoPairsInsert('[')<CR>
i  ]           *@<C-R>=AutoPairsInsert(']')<CR>
i  `           *@<C-R>=AutoPairsInsert('`')<CR>
i  {           *@<C-R>=AutoPairsInsert('{')<CR>
i  }           *@<C-R>=AutoPairsInsert('}')<CR>
i  <BS>        * <SNR>82_OnDeleteChar( "\<BS>" )
i  <C-Space>   * <C-R>=<SNR>82_InvokeSemanticCompletion()<CR>
i  <Nul>         <C-Space>
i  <S-Tab>     * pumvisible() ? "\<C-P>" : "\<S-Tab>"
i  <Plug>AutoPairsReturn & <SNR>50_AutoPairsReturn
i  <SNR>50_AutoPairsReturn * <C-R>=AutoPairsReturn()<CR>
i  <Down>      * pumvisible() ? "\<C-N>" : "\<Down>"
i  <Up>        * pumvisible() ? "\<C-P>" : "\<Up>"
i  <C-H>       * <SNR>82_OnDeleteChar( "\<C-H>" )
i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
i  <CR>        * ~<BS><CR>
i  <C-Y>       * <SNR>82_StopCompletion( "\<C-Y>" )
i  <Esc>x      * <Esc>x
i  <Esc>       * ~<BS><Esc>
```

**Comment by reujab** [comment]
It looks like you already have bindings for `<up>` and `<down>`. Try this:
```viml
inoremap <expr> <up> pumvisible() ? "\<c-n>" : "~\<bs>\<up>"
inoremap <expr> <down> pumvisible() ? "\<c-p>" : "~\<bs>\<down>"
```

**Comment by Hacksaurus** [comment]
It doesn't seem to work... Sorry

**Comment by reujab** [comment]
I assume a plugin is conflicting with a keybinding. Does it work if you disable every plugin other than auto-pairs? If so, enable each plugin one by one until you find the culprit.

**Comment by Hacksaurus** [comment]
I have disabled all of the plugins other than auto-pairs, and the issue still persists...
The conflict may be with auto-pairs, should we reopen this if that is the case?

**Comment by reujab** [comment]
If you use `inoremap <up> ~` does it type out a `~` when you press the up arrow key? If not, disable auto-pairs and try again. Try the same thing with `inoremap <expr> <up> "~"`.

What happens if you try your configuration with [Neovim](https://neovim.io/)?

Can you put your entire `.vimrc` in a [Gist](https://gist.github.com/) or repository?

**Comment by Hacksaurus** [comment]
Alright, so both
```
inoremap <up> ~
inoremap <expr> <up> "~"
```
Create `~`, whenever the up key is pressed when in insert mode.

Here is my entire `.vimrc`: http://termbin.com/hbsn

**Comment by reujab** [comment]
I was able to reproduce the issue using your `.vimrc`. It seems the culprit was YouCompleteMe. I'm pretty confident applying the following patch to your `.vimrc` will fix the issue.
```diff
--- before.vim	2017-09-04 19:13:52.890196229 -0400
+++ after.vim	2017-09-04 19:35:18.980202073 -0400
@@ -18,6 +18,8 @@
 inoremap <esc> ~<bs><esc>
 inoremap <cr> ~<bs><cr>
 inoremap <Esc>x <Esc>x
+inoremap <expr> <up> pumvisible() ? "\<c-p>" : "~\<bs>\<up>"
+inoremap <expr> <down> pumvisible() ? "\<c-p>" : "~\<bs>\<down>"
 
 "Commands
 command Copy :w | !clear && cat "%" | xclip -selection c
@@ -80,6 +82,8 @@
 "YouCompleteMe
 let g:ycm_autoclose_preview_window_after_completion = 1
 let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/ycm_extra_conf.py'
+let g:ycm_key_list_select_completion = ['<tab>']
+let g:ycm_key_list_previous_completion = ['<s-tab>']
 let g:ycm_show_diagnostics_ui = 0
 
 "Airline
```

**Comment by Hacksaurus** [comment]
Thank you so much!
It works perfectly now!
Thanks again!

Closing this thread
