### ISSUE TITLE
Is it possible to not auto pair " while editing .vim file?

### ISSUE THREAD

**Issue by nikitavoloboev** [jiangmiao/auto-pairs#204]
Since `"` is used to make a comment in vimrc, it's really annoying to have it auto expand two `"` every time.

**Comment by coachshea** [comment]
define an auto command for b:AutoPairs and leave out "

```vim
au filetype vim let b:AutoPairs = {'(':')', '[':']', '{':'}',"'":"'", '`':'`'}
```

**Comment by nikitavoloboev** [comment]
Thank you.
