### ISSUE TITLE
Auto indent on Return

### ISSUE THREAD

**Issue by Adel-Wehbi** [jiangmiao/auto-pairs#215]
I encountered this issue while using vim to write python.

`obj = {|}`

I click Return and instead of the expected: 
```
obj = {
    |
}
```
I get:
```
    obj = {
        |
    }
```
All three lines are indented.

I'm not sure if I was doing something wrong but thought to point this out anyways.

I "fixed" this by changing line 410 of the plugin file from:
`return "\<ESC>".cmd."=ko"`
to:
`return "\<ESC>".cmd."ko\t"`

**Comment by archification** [comment]
Mine wasn't tabbing at all. The same change on line 410 fixed it.

**Comment by ekiefl** [comment]
Thank you for making this issue and also for solving it.

**Comment by mbkupfer** [comment]
I'm having this issue as well and I just installed the latest version today.

**Comment by ekiefl** [comment]
@Adel-Wehbi I think you should keep this issue open as this isn't a great solution.

**EDIT**: I found the underlying problem, at least for my case.

I found that putting these two lines in my `~/.vimrc` have the potential to fix the issue:

```
set indentexpr=
set smartindent
```

If they do not, try something seemingly silly: `:so ~/.vimrc`. Did that fix it? If so, one of your plug-ins overwrites your initial settings when vim is first opened. You can find out by reopening vim and typing:

```
:verbose set smartindent? indentexpr?
```

For me, python filetype settings were messing things up, so I made the following file in `~/.vim/after/plugin/python.vim`:

```
set indentexpr=
set smartindent
```

This fix the problem for me. What I noticed is that if I remove `set smartindent` from this file, then @archification's fix _did_ work. So if you're experiencing this problem and you don't want `smartindent`, then use @archification's fix. If you want `smartindent`, then use this fix.

Your mileage of course will vary but hopefully this sheds at least some diagnostics on the issue.

**Comment by laoshaw** [comment]
neither worked for me, python is the only filetype I could not indent correctly.
