### ISSUE TITLE
auto-pairs will delete wrong quotes

### ISSUE THREAD

**Issue by RicardoMing** [jiangmiao/auto-pairs#230]
After this commit 179520e6907c5c0e5bf723236fccf250243316bb , auto-pairs will delete quotes which they shouldn't be deleted. 
For example, in the following `test.vim` file
```
" some comments
"|
" some other comments
```
| is the cursor position. If I press \<Backspace> key, it becomes
```
" some comments
 |some other commets
```

**Comment by jiangmiao** [comment]
For vim file use 
`au FileType vim      let b:AutoPairs = AutoPairsDefine({'\v^\s*\zs"': ''})` 
to handle "
or use `s` modifier
