### ISSUE TITLE
Triple backticks not working

### ISSUE THREAD

**Issue by sloria** [jiangmiao/auto-pairs#234]
I updated to the latest master (453d4889876cb89), and I noticed that triple backticks in Markdown no longer get paired properly.

May be related to https://github.com/jiangmiao/auto-pairs/issues/229 .

**Comment by jiangmiao** [comment]
You should define it it .vimrc

**Comment by sloria** [comment]
Ah ok, I see built-in support for triple backticks was removed https://github.com/jiangmiao/auto-pairs/commit/738d1f18a8cc6b3f8e0597304e0b2bce7c107dce .

The following worked:

```viml
autocmd FileType markdown let b:AutoPairs = AutoPairsDefine({'```' : '```'})
```

👍 Thanks for all your work on this project!
