### ISSUE TITLE
Can't insert â with autopairs loaded

### ISSUE THREAD

**Issue by dhilst** [jiangmiao/auto-pairs#240]
When autopairs is loaded I can't insert `â`. I'm on MacOS, I don't really know if this is something OS specific. Is very easy to reproduce, just type â and it will not put the desired character. It seems to be triggering some kind of keybind

Regards,

**Comment by frazrepo** [comment]
Confirmed , i have the same issue on Windows or Linux.
Type â and auto-pairs changed it to 0

**Comment by jiangmiao** [comment]
Duplicate of #88

**Comment by dhilst** [comment]
There is a solution at #88 

Thanks @jiangmiao !
Closing
