### ISSUE TITLE
When creating a list in python, auto-pairs cannot insert '' characters without jumping to next '

### ISSUE THREAD

**Issue by carlashley** [jiangmiao/auto-pairs#258]
When I'm creating a list in a python document, such as `['hello', 'world']`, and I go to insert another list element between the two existing elements, I cannot simply insert `'',` before the `'world'` element without auto-pairs jumping the cursor to the first `'` in the `'world'` string.
For example, I want to make the list `['hello', 'banana', 'world']`.

This has previously not been the case, and is actually quite frustrating, as I typically just want to insert the next element and close it out with the appropriate `,` when finished. What option exists to stop this jump forward? Is `let g:AutoPairsShortcutJump = 0` the correct mechanism?

**Comment by JonnyHaystack** [comment]
I find this frustrating too. The auto jump to a closing tag is nice, but this feels like something's going wrong internally and it thinks the opening quote is a closing quote? Intended or unintended, I find this behaviour is quite annoying and I can't think of a case where I'd want this to happen. If it's intended there should definitely be an option to disable this (maybe even disable it by default).
