### ISSUE TITLE
Opening bracket at start of a word should not auto close

### ISSUE THREAD

**Issue by santosh** [jiangmiao/auto-pairs#259]
I'm not sure if the configuration for this is already available. If so, please point me out. 

    input: (hello
    output: (|)hello
    expected output: (|hello

The point is, I want to wrap hello with `(` & `)`. And auto-pair is creating more problem (adding an extra step to delete `)`) than fixing it.

I would like to see it in auto-pair if it is not yet implemented. What do you say, guys?

Cheers! :clinking_glasses:

**Comment by xieshiyao** [comment]
What you need is `Fast Wrap`.

From `README.md`:
- Fast Wrap

```
input: |[foo, bar()] (press (<M-e> at |)
output: ([foo, bar()])
```

Similarly, you can do this:

```
input: |hello (press (<M-e> at |)
output: (hello)
```

But this is not obvious from the first example. I think they should consider adding my example into the document.

By the way, another solution is using `<M-p>` to disable auto-pairs temporary.

**Comment by santosh** [comment]
@xieshiyao `<M-e>` is Alt-e, right? It's opening edit menu (from menu bar) in my terminal.

> By the way, another solution is using `<M-p>` to disable auto-pairs temporary.

Thanks, that's somewhat helpful.

**Comment by xieshiyao** [comment]
Yes, it is.

Maybe you should change the shortcut of your terminal or set `g:AutoPairsShortcutFastWrap` to something else.
