### ISSUE TITLE
auto pairs not working in mac osx iterm2 or terminal

### ISSUE THREAD

**Issue by sunweik** [jiangmiao/auto-pairs#261]
Im using macvim 8.1.xxx or neovim 0.3.7 on mac osx, auto-pairs works great in GUI, but in iterm2 or terimnal auto-pairs doesn't auto pair. It is listed from :scriptnames, and g:autopairs-enabled is 1, somehow it just not working. Any further info is needed for debug?

**Comment by sunweik** [comment]
checked imap, all keys maps seems fine. for example

```
 ...
(    *@<C-R>=AutoPairsInsert('(')<CR>
...
```

**Comment by sunweik** [comment]
nvm, I think something is my .vimrc screwed it.

**Comment by sunweik** [comment]
"set paste" stopped auto-pairs working in console, is there a way to fix ti? or any workaround?

**Comment by JiaoZiLang** [comment]
After searching for a long time, I found that the key was set to cause the plugin not to work

**Comment by alexsmartens** [comment]
facing the same problem, `set paste` is used by the other plugin that I'm using ([vim-system-copy](https://github.com/christoomey/vim-system-copy)).

Is there any way to make auto-closing work with `set paste`?
