### ISSUE TITLE
How to install this with dein?

### ISSUE THREAD

**Issue by lakkiy** [jiangmiao/auto-pairs#275]
I add this `call dein#add('jiangmiao/auto-pairs')` to my vim config file but when i run `:call dein#install()` it shows 

> [dein] Target plugins are not found.

>[dein] You may have used the wrong plugin name, or all of the plugins are alread
y installed.

NVIM v0.4.3

**Comment by jrodval123** [comment]
Would you mind explaining how you fixed the issue?

**Comment by lakkiy** [comment]
Jesus Rodriguez ***@***.***> writes:

> Would you mind explaining how you fixed the issue?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.
>

Sorry I'm a emacs user now xD

-- 
Liu Bo

**Comment by LunarWatcher** [comment]
Assuming everything else is OK, it sounds like a dein problem that should be reported there. The plugin declaration line appears to be correct, so there's either something wrong with how dein is used, or something wrong with dein itself. I don't know though, I don't use dein.

That said, I personally recommend vim-plug instead (or in general, anything but dein). Vim-plug just works

**Comment by jrodval123** [comment]
Yeah... I might end up switching to vim-plug instead

**Comment by jrodval123** [comment]
> Jesus Rodriguez ***@***.***> writes:
> Would you mind explaining how you fixed the issue? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.
> Sorry I'm a emacs user now xD
> […](#)
> -- Liu Bo

I come from emacs lol
