### ISSUE TITLE
nested brackets are broken

### ISSUE THREAD

**Issue by Kyle-Thompson** [jiangmiao/auto-pairs#282]
In the following c++ code

```
int main() {
    if (something) {|}
}
```
where the cursor is at the `|` character, hitting enter will produce this result instead of what would be expected.

```
int main() {

    |  <- cursor
    if (something) {}
}
```

Any help is appreciated.

**Comment by xieshiyao** [comment]
Works fine for me. Maybe `auto-pairs` conficts with others plugins you are using.

**Comment by Kyle-Thompson** [comment]
I'll close this for now if it's not an issue with the plugin itself and I'll report back if I ever figure out the cause.
