### ISSUE TITLE
Enter key conflict with youcompleteme

### ISSUE THREAD

**Issue by zxYin** [jiangmiao/auto-pairs#285]
Both endwise and [youcompleteme](https://github.com/ycm-core/YouCompleteMe) bind the Enter key in insert mode when I set the Enter key as the stop completion key in ycm:
```
let g:ycm_key_list_stop_completion = [ '<C-y>', '<Enter>' ]
```
If I want to select a completion in ycm by tabbing the Enter key, it will start a new line instead of select the completion, even I don't type any brackets. How can I make them both work? Thanks.

**Comment by AlexAegis** [comment]
I experience a similar issue with `coc`. When I accept an autocompletion using <cr> (Inside quotations) it inserts a new line before, but only if the previous line is not empty.

**Comment by mrbeardad** [comment]
For YCM, add the following code to your ***init.vim*** or ***vimrc***, 

```vim
let g:ycm_key_list_stop_completion = ['<s-cr>']
let g:AutoPairsMapCR = 0
function! Ycm_and_AutoPair_Return()
  if expand('<cword>') == '{}'
    return "\<CR>"
  else
    exe 'return '. substitute(substitute(execute('imap <s-cr>'),'^.*<SNR>','<SNR>', ''),'S-CR','CR','')
  endif
endfunction

inoremap <silent><cr> <c-r>=Ycm_and_AutoPair_Return()<cr><c-r>=AutoPairsReturn()<cr>

```

**Comment by rodhash** [comment]
> For YCM, add the following code to your _**init.vim**_ or _**vimrc**_,
> 
> ```viml
> let g:ycm_key_list_stop_completion = ['<s-cr>']
> let g:AutoPairsMapCR = 0
> function! Ycm_and_AutoPair_Return()
>   if expand('<cword>') == '{}'
>     return "\<CR>"
>   else
>     exe 'return '. substitute(substitute(execute('imap <s-cr>'),'^.*<SNR>','<SNR>', ''),'S-CR','CR','')
>   endif
> endfunction
> 
> inoremap <silent><cr> <c-r>=Ycm_and_AutoPair_Return()<cr><c-r>=AutoPairsReturn()<cr>
> ```

Thank you!
