### ISSUE TITLE
Wrap parentheses around existing word

### ISSUE THREAD

**Issue by antoyo** [jiangmiao/auto-pairs#287]
Hi.
Let's say I have the following:
```c
10
```
And I want to transform it into:
```c
function(10)
```
How would I do that?

If I type `function(` before `10` I get:
```c
function()10
```
Which is not what I want.
Thanks.

**Comment by dseeni** [comment]
There are mapping for that already set these commands:
let g:AutoPairsShortcutToggle= <M-p>
let g:AutoPairsShortcutFastWrap= <M-e>
let g:AutoPairsShortcutJump= <M-n>
let g:AutoPairsShortcutBackInsert= <M-b>

Fast wrap is what you want
