### ISSUE TITLE
Markdown todo list

### ISSUE THREAD

**Issue by gbirke** [jiangmiao/auto-pairs#288]
I'm creating TODO lists in Github-Feature markdown like this:

```
- [ ] first item
- [ ] second item
```

After I type "`[ `", I get another space before the closing bracket, Which I the have to forward-delete. Is there any way to avoid the 2nd space in this specific instance (markdown document, line matching the regex `\s*-\[`)?

**Comment by michaelfreyj** [comment]
I don't have this same issue. If you type `[ ]` does the second space not disappear after your hit the closing bracket key?

**Comment by gbirke** [comment]
Ah, that solves it! I'm using a German keyboard and had hoped to be able to skip typing the awkward closing brace, moving the cursor instead. 

As a small consolation I'll use a different `comment` option that'll auto-continue the list:
`:set comments=b:>,b:*,b:+,b:-`
