### ISSUE TITLE
Breaks '.'

### ISSUE THREAD

**Issue by srushti** [jiangmiao/auto-pairs#3]
I'm not sure if this is even fixable (and I've faced similar issues with other pairing plugins), but could it possibly be made to work with '.'.
Currently if I type ''i[Hello world]<esc>' and then hit '.' I only get the 'Hello World' and not the brackets. I understand they work as different actions, but unfortunately vim users are used to thinking of an insert action as a repeatable command.
This becomes even more tricky if you use this as part of a 'cw' (change word) type command, because it forgets the changing part of the action.

**Comment by ptrin** [comment]
@jiangmiao Is it necessary to use <LEFT>? Have you looked at getpos() and setpos() to move the cursor?

**Comment by jiangmiao** [comment]
@ptrin I've tested code. But it cannot work. The function action won't be recorded. The code `(foo)` will be repeated as `()foo`

**Comment by unphased** [comment]
So for future reference, using Ctrl+V to circumvent auto-pairs does work and as long as you are careful to not trigger autopairs by escaping each of these open parens/brackets with Ctrl+V they will land in the dot register properly.

**Comment by chrisbra** [comment]
Note: Starting from version [7.4.849](https://github.com/vim/vim/releases/tag/v7.4.849) you can use `<C-G>Cursor` to move within a line and not break undo/redo

**Comment by muffinmad** [comment]
@chrisbra `<C-g>U<cursor>` maybe?
@jiangmiao Take a look at `:help i_CTRL-G_U` please

**Comment by chrisbra** [comment]
@muffinmad yes

**Comment by jiangmiao** [comment]
The issue should be fixed now.

**Comment by unphased** [comment]
Works great but only in nvim and not vim? Can anyone confirm?

**Comment by muffinmad** [comment]
@unphased Works fine in vim 7.4.1639. You need at least vim 7.4.849 i guess.

**Comment by ianwitherow** [comment]
It seems like new lines within a pair breaks repeating with '.'. Has anyone else experienced this?

For example:

```
function moo() {
    |  <- cursor
}
```

Pressing '.' after that only enters a blank line. Any ideas?
