### ISSUE TITLE
Disable some pairs in spesific filetype

### ISSUE THREAD

**Issue by ahmadshiddiq** [jiangmiao/auto-pairs#300]
I want to disable `"` in `.vim` file.
Every want to make a comment always be generate 2 `"`

**Comment by skbolton** [comment]
Same solution in #109 would work here

**Comment by ahmadshiddiq** [comment]
Thanks it works.
Here my line :
`au FileType vim let b:AutoPairs={'(':')', '[':']', '{':'}', "'":"'", "`":"`", '```':'```', "'''":"'''"} " Disable auto close quote`
