### ISSUE TITLE
Disable Auto Pairs automatically in a directory

### ISSUE THREAD

**Issue by ayushxx7** [jiangmiao/auto-pairs#310]
Is there a way I can disable auto-pairs in a directory by default, but not affect the global settings elsewhere?
For instance, whenever I am in the vim config folder `$HOME\.config\vim` I don't want Auto Pairs to be running.

**Comment by ayushxx7** [comment]
Hi @jiangmiao, how to use the `g:AutoPairsDirectoryBlacklist` config?
I have tried by adding: 
```
let g:AutoPairsDirectoryBlacklist = ['$HOME\.config\vim']
```

and 
```
let g:AutoPairsDirectoryBlacklist = ['$HOME\\.config\\vim']
```

But neither option seems to change the behavior.

**Comment by LunarWatcher** [comment]
The change was made in my fork. jiangmiao is MIA (see #309), so the change will therefore not be merged even if I made a PR. You'll have to switch to the fork if you wanna use it

**Comment by ayushxx7** [comment]
Hi @LunarWatcher, I switched to the fork, but the setting still doesn't apply for some reason. I've tried with both settings mentioned above. What am I doing wrong?

**Comment by LunarWatcher** [comment]
`$HOME` is probably not expanded in the string. Try `let g:AutoPairsDirectoryBlacklist = [$HOME . '\.config\vim']`

**Comment by ayushxx7** [comment]
Yes, thanks! That worked 👍

**Comment by ayushxx7** [comment]
If anyone faces a similar problem, take a look at [LunarWatcher's fork](https://github.com/LunarWatcher/auto-pairs) of this plugin.
