### ISSUE TITLE
Is there an easy way to disable pairs for one instance?

### ISSUE THREAD

**Issue by jeffwillette** [jiangmiao/auto-pairs#324]
I like this plugin and I find that it helps me about 80% of the time, but for about 20% of the time I actually don't want it to add any pairs and just literally type what I type... For example, let say I had a correctly paired code block and then during editing I deleted one of the pairs like so...

```
# step 1
foo = [ <-- delete this line for some reason
"bar",
"baz",
]

# step 2
foo2 = [] <-- auto pairs adds this when I retype the correct line 
"bar",
"baz",
]
```

When auto pairs does this it requires me to manually delete the added pairs which happens quite often in practice. Is there a way to ignore that pair when I retype the line so that I don't have to delete the closing brace that auto-pairs addded?

**Comment by LunarWatcher** [comment]
https://github.com/jiangmiao/auto-pairs/blob/master/doc/AutoPairs.txt#L175

**Comment by jeffwillette** [comment]
oh cool, does `<M-p>` mean a literal 'M' or is that some keycode?

**Comment by LunarWatcher** [comment]
`:h <M-`
