### ISSUE TITLE
hitiing <CR> at {|} doesn't making a new line

### ISSUE THREAD

**Issue by arpangreat** [jiangmiao/auto-pairs#327]
when we hit <CR> at {|} the output should be like this ..
{
   |
}

But for me it is  not working like that , any suggestions ??

P.S. :-  I am using nvim 0.5 with LSP and nvim-compe and completion nvim

**Comment by LunarWatcher** [comment]
What's the output of `:verbose imap <CR>`?

**Comment by arpangreat** [comment]
The bug was with completion-nvim ...

In which completion-nvim set the completion confirm key to <CR> which overwrites auto pairs .

The solve was like this 

```vim
let g:completion_confirm_key = ""
imap <expr> <cr>  pumvisible() ? complete_info()["selected"] != "-1" ?
                 \ "\<Plug>(completion_confirm_completion)"  : "\<c-e>\<CR>" :  "\<CR>"

```
or in lua config 
```lua
vim.cmd([[let g:completion_confirm_key = ""]])
vim.cmd([[
imap <expr> <cr>  pumvisible() ? complete_info()["selected"] != "-1" ? "\<Plug>(completion_confirm_completion)"  : "\<c-e>\<CR>" :  "\<CR>"
]])
```

Thanks for your help 🤗🤗

**Comment by arpangreat** [comment]
closing this issue.
