### ISSUE TITLE
Don't go to the closing bracket when it's on the next line

### ISSUE THREAD

**Issue by aj3423** [jiangmiao/auto-pairs#328]
Sometimes the code looks like:
```
{
	{
		some code
		|  <---  cursor here
}
```
When type a "}" at that position, it doesn't insert a "}", it goes to the next line. 
Currently I just go to the last line, copy the "}" line by *yy* and paste *p*, let the linter do the indention.

Maybe not go to the followed "}" if the "}" is on the next line ?

**Comment by LunarWatcher** [comment]
[Shitty standards](https://github.com/jiangmiao/auto-pairs/blob/master/doc/AutoPairs.txt#L318-L325) (read: `let g:AutoPairsMultilineClose = 0`).

[My fork](https://github.com/LunarWatcher/auto-pairs) does this by default, as well as enabling a keybind for toggling it.
