### ISSUE TITLE
Fast wrap not working in Windows Subsystem for Linux 2 (wsl2)

### ISSUE THREAD

**Issue by comiluv** [jiangmiao/auto-pairs#331]
Environment:
Windows 10 [Version 10.0.19043.1110]
WSL2 kernel version 5.10.16.3
Ubuntu 20.04
VIM version 8.1.2269
https://github.com/junegunn/vim-plug

I had to add below lines in .vimrc to map alt key combination to M- modifier, as described in [this stackoverflow answer](https://stackoverflow.com/questions/49052619/any-mapping-in-vimrc-with-alt-isnt-working)
```
if has('unix')
    map <Esc>e <M-e>
    map <Esc>p <M-p>
    map <Esc>n <M-n>
    map <Esc>b <M-b>
    map <Esc>j <M-j>
    map <Esc>k <M-k>
endif
```
Fast wrapping doesn't work in above environment, as shown in screenshot below.
![inubuntu](https://user-images.githubusercontent.com/19642705/128536715-ed5ac36f-2e45-448b-87b5-554a02d2141f.gif)

Pressing alt key combination works in Ubuntu in wsl in Windows 10, as pressing Alt-p works to disable/enable auto-pairs, and shown in below screenshot for pressing Alt-e:
<img width="374" alt="화면 캡처 2021-08-07 004822" src="https://user-images.githubusercontent.com/19642705/128537297-d991013e-ec05-49bf-b847-65a64e812a7f.png">

Plugin works in other environments, such as in gVim:
![ingvim](https://user-images.githubusercontent.com/19642705/128536750-d441ee3f-3845-427e-bf78-f531ce112db9.gif)

and in Powershell using vim for windows that comes with gVim:
![inpwsh](https://user-images.githubusercontent.com/19642705/128536911-409f6465-fc75-43df-90d4-c86de4bbc158.gif)

**Comment by LunarWatcher** [comment]
> Pressing alt key combination works in Ubuntu in wsl in Windows 10, as pressing Alt-p works to disable/enable auto-pairs, and shown in below screenshot for pressing Alt-e:

Sooo what's the problem if everything works? 

Don't forget `verbose imap <M-e>`

**Comment by comiluv** [comment]
> > Pressing alt key combination works in Ubuntu in wsl in Windows 10, as pressing Alt-p works to disable/enable auto-pairs, and shown in below screenshot for pressing Alt-e:
> 
> Sooo what's the problem if everything works?
> 
> Don't forget `verbose imap <M-e>`

I can see I'm pressing Alt-e in console using sed -n l, but plugin won't run fast wrap 😢 
```verbose imap <M-e>``` shows me:
```
i  <M-e>       *@<C-R>=AutoPairsFastWrap()<CR>
        Last set from ~/.vim/plugged/auto-pairs/plugin/auto-pairs.vim line 562
```

**Comment by comiluv** [comment]
Updated Vim version in Ubuntu to 8.2.2815 to no avail.
Installed neovim version 0.6.0 and it works with neovim in Ubuntu.
![inneovim](https://user-images.githubusercontent.com/19642705/128597503-0d9ab825-3652-4485-b748-d2710d26ef30.gif)

**Comment by LunarWatcher** [comment]
Sounds like a Vim bug then. [Open an issue there](https://github.com/vim/vim/) instead

**Comment by comiluv** [comment]
Probably a bug in Vim. See https://github.com/vim/vim/issues/8726

**Comment by chrisbra** [comment]
please describe exactly what the vim bug should be

**Comment by LunarWatcher** [comment]
If it works in Neovim, but not in Vim, in the same terminal, in the same Linux subsystem, it's reasonable to assume it's something preventing Vim from properly handling the input. Especially when considering it's status-norepro seemingly everywhere but Vim (and not Neovim) in WSL. I'm on a Linux machine though, so I can't verify.

**Comment by comiluv** [comment]
The problem is solved by using different remapping method which you can read in https://github.com/vim/vim/issues/8726, which I think is a work-around, as I could pass Alt key combinations to execute other commands successfully even with my original remappings. Nonetheless, the problem at hand is solved.
