### ISSUE TITLE
Conflict with Input Method

### ISSUE THREAD

**Issue by zeoxion** [jiangmiao/auto-pairs#334]
When I use this plug my input method may have some problems that it will automatically transfer english to chinese when I type space.

**Comment by LunarWatcher** [comment]
Really need some more context here.

What OS? What input method? What keybind conflicts? Where is space a problem?

**Comment by zeoxion** [comment]
windows 10
the input methods is flypy:https://www.flypy.com/ and the rime also has the smae problems
I use `Shift` to switch the language
And I have tried another plug: https://github.com/Raimondi/delimitMate and there is a similar problem:
when I type `cr` the input method will automatically switch form english to chinese...

**Comment by zeoxion** [comment]
I think there must be something worng with the win10 or gvim or something else. I have the same problem again and find out that another plug can also lead to this problem, which didn't occour before. So I think there is no use to debug. Thank you anyway!
