### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by asadmoosvi** [jiangmiao/auto-pairs#336]
I haven't seen any updates in this repo for quite some time given the number of issues. Also there are a lot of weird bugs which makes it hard to use. I cannot find an alternative plugin that is as fast as this one though.

Is there a fork of this project that is well maintained and that the community recommends using instead?

**Comment by LunarWatcher** [comment]
#309

**Comment by asadmoosvi** [comment]
So your fork is the recommended one that I should use instead?

**Comment by LunarWatcher** [comment]
Dunno about recommended (I mean, I recommend it, but I'm biased), but it's the only maintained fork at the moment.
