### ISSUE TITLE
Not auto pair when code in Rust file

### ISSUE THREAD

**Issue by hungpham3112** [jiangmiao/auto-pairs#337]
When I edit the Rust file, I used `b' '` in the `if ` statement but it didn't work

![bandicam 2021-09-02 21-33-05-390](https://user-images.githubusercontent.com/75968004/131863080-4ef63722-1ba4-4934-a0a7-b1cb3d3749e0.gif)

It's really uncomfortable

**Comment by LunarWatcher** [comment]
[My fork](https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L988-L1003) has a system to deal with these edge-cases. `b` is included by default, so the expansion works.

However, [Rust is annoying](https://github.com/rust-lang/rust.vim/blob/87c745d8d506fc1eecc1d81df15d5bde1658a2fc/ftplugin/rust.vim#L77-L79) and decided to override the default pairs in a way that completely disregards auto-pairs and user standards.

Use `let g:rust_keep_autopairs_default = 1` to keep general single quote completion

**Comment by hungpham3112** [comment]
> [My fork](https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L988-L1003) has a system to deal with these edge-cases. `b` is included by default, so the expansion works.
> 
> However, [Rust is annoying](https://github.com/rust-lang/rust.vim/blob/87c745d8d506fc1eecc1d81df15d5bde1658a2fc/ftplugin/rust.vim#L77-L79) and decided to override the default pairs in a way that completely disregards auto-pairs and user standards.
> 
> Use `let g:rust_keep_autopairs_default = 1` to keep general single quote completion

It doesn't work, still auto-pairs single quote

**Comment by LunarWatcher** [comment]
Works fine for me out of the box with no config to auto-pairs. Did you actually switch repos? Remember that you need to clean before installing

**Comment by hungpham3112** [comment]
> Works fine for me out of the box with no config to auto-pairs. Did you actually switch repos? Remember that you need to clean before installing

Thanks for your fork, sorry for really late respond, . I'm using your fork now.  `let g:rust_keep_autopairs_default = 1` solved my problems. But I don't see help file of `rust_keep_autopairs_default` in the document when press K in vim. Keep up the great work !!!

**Comment by LunarWatcher** [comment]
Auto-pairs doesn't currently document it, because it's created by and in the rust plugin. Consequently, that's where the docs are: https://github.com/rust-lang/rust.vim/blob/87c745d8d506fc1eecc1d81df15d5bde1658a2fc/doc/rust.txt#L277

That said, I'll add a troubleshooting section on it (if I haven't already; I don't remember). It's hard to find from Rust's docs, and the troubleshooting doc is a more natural place to look anyway
