### ISSUE TITLE
Breaks Return in markdown

### ISSUE THREAD

**Issue by exchgr** [jiangmiao/auto-pairs#34]
In a markdown file, instead of creating a new line when the return key is pressed, auto-pairs spits out `<SNR>57_Return()`

**Comment by laoshaw** [comment]
I installed an autocomplete plugin for C++ (Plug 'xavierd/clang_complete'),  it works,  now after I used the first ctrl-N to do a random autocomplete then hit an enter key, I immediately saw "<SNR>38_AutoPairsReturn", how can I fix this? I really want to have both clang_complete and auto-pairs installed if they can indeed co-exist.
