### ISSUE TITLE
Disabling specific auto pairs doesn't work

### ISSUE THREAD

**Issue by Yugeniki** [jiangmiao/auto-pairs#340]
It says in documentation I should be able to disable globally via `let g:AutoPairs` but it doesn't work, it also says I should be able to disable for file types via something like `au filetype vim let b:AutoPairs = {'(':')', '[':']', '{':'}', '``':"''"} ` but that also doesn't work, help?

**Comment by LunarWatcher** [comment]
Works fine for me. What's your config like?

**Comment by Yugeniki** [comment]
![image](https://user-images.githubusercontent.com/39875439/137006061-e30175f4-60cb-42ec-8eaf-a28fe39836ca.png)
![image](https://user-images.githubusercontent.com/39875439/137006092-d580d739-6587-4aa1-9b7a-99ac7a8a4e3a.png)
The relevant parts are like this but ` still works. as does ' and "

**Comment by LunarWatcher** [comment]
This isn't nvim-autopairs - auto-pairs is probably overridden by the other plugin, if you're using both. In that case, pick one and stick to it. Otherwise, you're probably looking for https://github.com/windwp/nvim-autopairs

**Comment by Yugeniki** [comment]
Oh, sorry for the bother.
