### ISSUE TITLE
With which command to disable?

### ISSUE THREAD

**Issue by Congstarrr** [jiangmiao/auto-pairs#344]
With which command can I disable autopairs? I want to disable them for all .tex files and hence create an autocmd that does this, I just can't find the corresponding command.

**Comment by LunarWatcher** [comment]
You can use `AutoPairsToggle` or `b:autopairs_enabled` to control auto-pairs. See also #128. That said, my fork has support for a filetype blacklist if you don't want to use manual autocmds. See: https://github.com/LunarWatcher/auto-pairs/blob/8c4a035165a5af726bbcc60c78821a66083a9f98/doc/AutoPairs.txt#L1255-L1264

**Comment by Congstarrr** [comment]
@LunarWatcher  Thanks a lot, I stupidly wrote `g:autopairs_enabled` which is why it didn't work earlier. Great extension!
