### ISSUE TITLE
Pressing enter to autocomplete inserts actual enter character

### ISSUE THREAD

**Issue by cubetastic33** [jiangmiao/auto-pairs#346]
When I press enter to autocomplete from the autocomplete menu, the suggestion gets autocompleted, but an actual enter character also gets inserted along with it. Here's a screenshot of the autocomplete menu:
![image](https://user-images.githubusercontent.com/33519300/158857746-4c8f775d-1d5c-4a90-99f0-9b3cdaa0310b.png)
When I press enter, the text "testing" gets filled, and the cursor moves to the next line. If I uninstall the auto-pairs plugin and try the same thing, the text "testing" gets filled, and the cursor stays on the same line. How do I fix this behavior? Is there a config flag or something I can change?

Also, pressing ctrl + h deletes characters when auto-pairs is installed - if I uninstall it, the keybind works as expected (it's a keybind in the autocomplete extension I use, coq). However, I couldn't find ctrl + h mentioned anywhere as a shortcut in the README of this plugin. Why does this happen? Or should I make a separate issue about this since it's another question?

**Comment by n0ks** [comment]
Just set  ``` let g:AutoPairsMapCR = 0 ``` to disable ```<CR>``` mapping.

That's my workaround while im lazy to switch to nvim-autopairs.

**Comment by cubetastic33** [comment]
Okay, thank you!
