### ISSUE TITLE
Bug with double quotes (windows)

### ISSUE THREAD

**Issue by OrionGonzalez** [jiangmiao/auto-pairs#354]
It works fine for all others, but when I try it with `"` it has unexpected behaviour: The first time you press " it only makes one, the second it makes two:

https://user-images.githubusercontent.com/107467569/191941547-beff70bf-6231-4fdc-91f7-439817c54878.mp4

**Comment by LunarWatcher** [comment]
" is special because it's also the comment character in Vim. My fork has an expanded regex for checking comment balancing, but it isn't easy. Legacy Vimscript is a royal pain to do sane " balancing with
