### ISSUE TITLE
g:AutoPairsShortcutToggle limit it in normal mode only

### ISSUE THREAD

**Issue by pinggit** [jiangmiao/auto-pairs#356]
currently when I set
```
let g:AutoPairsShortcutToggle = ',aP'
```

it works in both normal mode and insert mode, when I quickly type `,aP`
but this will slow down my typing whenever I need to type `,`.
what I hope is to make it only work in normal mode.

is it possible?

**Comment by LunarWatcher** [comment]
No, but it doesn't actually slow you down. If you keep typing and don't type ,aP, vim automatically figures out you didn't mean the command and inserts the characters. The visual might be slightly misleading there, but you don't have to wait for the command to time out.

**Comment by pinggit** [comment]
got it. sounds making sense.
I also tried to disable insert mode mapping:

`iunmap <buffer> ,aP`

it works if I do it after vim started, but if I put it in vimrc it reports
errors when vim starts up, says there is no such mapping.
I guess I should put it somewhere where vim will read only after everything
is up and running...

**Comment by LunarWatcher** [comment]
Yep, but also no. The map is a buffer mapping, which honestly is a weird decision for a toggle. You can just disable the map and manually create the nmap: 

https://github.com/jiangmiao/auto-pairs/blob/master/plugin/auto-pairs.vim#L569-L573

I.e. `let g:AutoPairsShortcutToggle = ""` and `nnoremap <silent> ,aP :call AutoPairsToggle()<CR>` in your .vimrc instead.

**Comment by pinggit** [comment]
works well!
thanks.
