### ISSUE TITLE
conflict with coc.nvim auto-completion in some situation

### ISSUE THREAD

**Issue by wanaiqing** [jiangmiao/auto-pairs#361]
Auto-completion was messed up in certain situation, tested with minimal configuration in docker.

.vimrc
[vimrc.txt](https://github.com/jiangmiao/auto-pairs/files/10577324/vimrc.txt)

screen record

https://user-images.githubusercontent.com/20230818/216559910-8af712e2-1702-4927-94ac-f958abcca031.mp4

**Comment by LunarWatcher** [comment]
What's the output of
```
imap <cr>
imap <SNR>1234_AutoPairsOldCRWrapper1234
```
where `1234` is replaced with the numbers you see in `imap <cr>`?

**Comment by wanaiqing** [comment]
> What's the output of
> 
> ```
> imap <cr>
> imap <SNR>1234_AutoPairsOldCRWrapper1234
> ```
> 
> where `1234` is replaced with the numbers you see in `imap <cr>`?

the output of "imap \<cr>":
i  <CR>        &@<SNR>16_AutoPairsOldCRWrapper73<SNR>16_AutoPairsReturn
i  <CR>        * coc#pum#visible() ? coc#_select_confirm() : "\<C-G>u\<CR>"

the output of "imap \<SNR>16_AutoPairsOldCRWrapper73":
i  <SNR>16_AutoPairsOldCRWrapper73 &@coc#pum#visible() ? coc#_select_confirm() : "\
<C-G>u\<CR>"

**Comment by LunarWatcher** [comment]
Finally reproduced it. Looks like both SNRs are invoked, which sounds like the most plausible explanation.

You'll have to
```
let g:AutoPairsMapCR = 0
inoremap <silent><expr> <cr> coc#pum#visible() ? coc#_select_confirm() : "\<C-g>u\<CR><C-r>=AutoPairsReturn()\<cr>"
```

**Comment by wanaiqing** [comment]
> Finally reproduced it. Looks like both SNRs are invoked, which sounds like the most plausible explanation.
> 
> 
> 
> You'll have to
> 
> ```
> 
> let g:AutoPairsMapCR = 0
> 
> inoremap <silent><expr> <cr> coc#pum#visible() ? coc#_select_confirm() : "\<C-g>u\<CR><C-r>=AutoPairsReturn()\<cr>"
> 
> ```

Great! It's gone.

**Comment by wanaiqing** [comment]
Thanks. @LunarWatcher

**Comment by dr0bz** [comment]
@LunarWatcher Thank you very much. I had this issue as well.
