### ISSUE TITLE
error match for quotes

### ISSUE THREAD

**Issue by camarayol** [jiangmiao/auto-pairs#363]
input: |string"
When I press " at | 
output: "|"string"
But here's what I hope
output: "|string"

Is this possible? Thanks!

**Comment by LunarWatcher** [comment]
It's supported in my fork: https://github.com/LunarWatcher/auto-pairs

**Comment by samghara** [comment]
> It's supported in my fork: https://github.com/LunarWatcher/auto-pairs

I tried, it's supported, Thanks a lot!
