### ISSUE TITLE
javascript indentation

### ISSUE THREAD

**Issue by albertosantini** [jiangmiao/auto-pairs#45]
In javascript with nocindent, the indentation is "wrong".

Firstly without auto-pairs plugin:

```
// cindent
function () {
    var foo = {
        bar: {

             } // this line is not indented "correctly"
    }
}
```

```
// nocindent
function () {
    var foo = {
        bar: {

        } // ok
    }
}
```

With auto-pairs and nocindent the result is like setting cindent.

I think it is due to '=ko' in line 369:

```
return "\<ESC>=ko".cmd
```

https://github.com/jiangmiao/auto-pairs/blob/master/plugin/auto-pairs.vim#L369

Any thought?

Thanks in advance,
Alberto

**Comment by quangv** [comment]
I believe we have similar problems. Check out my fix on #85
