### ISSUE TITLE
Too big indentation on putting a new line after e.g. ({ <CR> })

### ISSUE THREAD

**Issue by pmalek** [jiangmiao/auto-pairs#54]
I have noticed that with your plugin using `Insert new indented line after Return` in e.g. `({ | })` I would get wrong indentation level. 

``` javascript
mydata.forEach(function(d){
  d.interval = +d.interval;
  })
```

How this can be corrected or adjusted to produce something like this : 

``` javascript
mydata.forEach(function(d){
  d.interval = +d.interval;
})
```

??

**Comment by reidcooper** [comment]
@mbrevda <3
