### ISSUE TITLE
Option to disable "Quick jump to closed pair"

### ISSUE THREAD

**Issue by littke** [jiangmiao/auto-pairs#74]
Thanks!

**Comment by pangdaxing23** [comment]
I agree, this behavior is _extremely_ annoying and unintuitive, and I find it happening all the time, at which point I have to look up the command to disable auto-pairs, or go into paste mode.
The simpler solution would be to just offer an option to disable the "quick jump" feature in the `.vimrc`

**Comment by subev** [comment]
Years later, still missing such option?

**Comment by amcsi** [comment]
@subev yes, I'm still using my own fork:
https://github.com/amcsi/vimfiles/blob/master/vimrc.vim#L41
https://github.com/amcsi/auto-pairs/commit/4c1a8996296ad2ce4549ae652abb3133a2df377c

**Comment by jiangmiao** [comment]
disable FlyMode and redefine all pairs in g:AutoPairs with `s` modifier. eg `'{':'}//s'`, then `}` will not jump through multiline

**Comment by amcsi** [comment]
These are the reasons I stopped using Vim as my main editor 😅 you constantly need to do complicated things in order to get simple results

**Comment by Mantissa-23** [comment]
Thanks jiangmiao

**Comment by iGEL** [comment]
I gave this plugin a shot, but this is a deal breaker for me. I will go back to https://github.com/Raimondi/delimitMate until there is an option to _never_ jump when I type parenthesis.

**Comment by mrbeardad** [comment]
**Add flowing code to you vimrc or init.vim can solve this problem.**
```vim
  if get(g:, 'AutoPairsFlyMode', 0) == 0
    function! s:replace_autopairs_map(char)
      let afterStr = strpart(getline('.'), col('.')-1)
      if afterStr =~ '^\s*'.a:char
        return a:char
      elseif afterStr =~ '^\s*$'
        let nextLineNum = getpos('.')[1] + 1
        let nextLine = getline(nextLineNum)
        while nextLineNum <= line('$') && nextLine =~ '^\s*$'
          let nextLineNum += 1
          let nextLine = getline(nextLineNum)
        endwhile
        if nextLine =~ '^\s*'.a:char
          return a:char
        else
          return AutoPairsInsert(a:char)
        endif
      else
        return AutoPairsInsert(a:char)
      endif
    endfunction

    function! s:disable_autopair_flymod()
      if b:autopairs_loaded < 2
        iunmap <buffer> }
        iunmap <buffer> ]
        iunmap <buffer> )
        iunmap <buffer> `
        iunmap <buffer> '
        iunmap <buffer> "
        inoremap <buffer> <silent> } <c-r>=<SID>replace_autopairs_map('}')<cr>
        inoremap <buffer> <silent> ] <c-r>=<SID>replace_autopairs_map(']')<cr>
        inoremap <buffer> <silent> ) <c-r>=<SID>replace_autopairs_map(')')<cr>
        inoremap <buffer> <silent> ` <c-r>=<SID>replace_autopairs_map('`')<cr>
        inoremap <buffer> <silent> ' <c-r>=<SID>replace_autopairs_map("'")<cr>
        inoremap <buffer> <silent> " <c-r>=<SID>replace_autopairs_map('"')<cr>
      endif
      let b:autopairs_loaded = 2
    endfunction

    augroup AutoPairs
      autocmd InsertEnter * call s:disable_autopair_flymod()
    augroup END
  endif

```
