### ISSUE TITLE
Extra <Esc> needed in AutoPairsReturn

### ISSUE THREAD

**Issue by yukunlin** [jiangmiao/auto-pairs#83]
Suppose that the cursor is somewhere near the bottom of the screen.

Type "{" in insert mode, and "{|}" will appear as expected, with the cursor inside the braces. Hit return and we get

{
    |
}

as expected. In addition, the document would have also automatically scrolled down as well. However, when AutoPairsJump() is called via the mapped key-sequences in insert mode, this happens:

![screen shot 2014-03-12 at 12 33 12 am](https://f.cloud.github.com/assets/3442461/2394673/25b0e204-a9b9-11e3-99fa-a9607d964b8c.png)

A video of the bug is linked here: http://youtu.be/D5Wu_P2rAWE

I think the fix is to replace

```
let cmd = " \<C-O>zz\<ESC>cl"
```

at line 358 of autopairs.vim with 

```
let cmd = " \<C-O>zz\<ESC>cl\<ESC>"
```

**Comment by Chun-Yang** [comment]
Hey @mjacobus , I have the SAME problem with you. 
I did another fix https://github.com/Chun-Yang/auto-pairs, you can check if out.

**Comment by mjacobus** [comment]
Thank you @Chun-Yang ! But actually I have been using [this](https://github.com/mjacobus/.dotfiles/blob/c900cf131ebe5bb2ef9a608ca591bc67dc02711d/vim/vimrc#L30) fork ever since I found that stackoverflow post and it works fine.

**Comment by yukunlin** [comment]
Has been fixed now by other commits made by the owner.
