### ISSUE TITLE
Mapping å

### ISSUE THREAD

**Issue by jsborjesson** [jiangmiao/auto-pairs#88]
Hi! This plugin is awesome and has helped me a bunch for a long time without problems, until I suddenly tried to write something in Swedish - this is when I noticed that this plugin maps the **å** key for some reason. 

Output of `:verbose imap å`

```
i  å           *@<C-R>=AutoPairsFastWrap()<CR>
        Last set from ~/Projects/dotfiles/vim/bundle/auto-pairs/plugin/auto-pairs.vim
```

Any idea why this is happening? Even an ugly hack to turn it off in the vimrc would solve this problem for me.

Thanks!

**Comment by relausen** [comment]
I have the exact same problem with Danish keyboards. Same letter ('å').

**Comment by etnoy** [comment]
Yep, same here. This bug is actually quite serious for Swedish users, since we can't even include one of our language's characters. Quite annoying.

**Comment by alcesleo** [comment]
Did you try remapping AutoPairsShortcutFastWrap like I suggested? I agree that it's a nuisance that it does this by default but it is easy to turn off.

**Comment by etnoy** [comment]
Yes, I did and it worked. However, it took some time to even find the :verbose imap å command, which finally led me here. It was quite confusing for a while, and should be fixed for real.

**Comment by alcesleo** [comment]
Yeah I agree, took me quite a while to figure it out too. I'm afraid this
might be a problem with how vim interprets the key press though, if it has
no way of determining the difference between å and <M-e> sent from the
terminal then it's not a problem with the plugin but a limitation of Vim
itself.

**Comment by eirikgje** [comment]
Norwegian clocking in here - same issue!

**Comment by gaspaio** [comment]
I have the same problem in french. In the end, i disabled autopairs completely in markdown and text files.

**Comment by alcesleo** [comment]
I had this issue with several other plugins too, I don't think there's anything the plugin authors can do about this since it's just the keycodes overlapping on non-US layouts. Putting this in your `.vimrc` after you load any plugins should hopefully solve it for good:

```viml
silent! iunmap å
silent! iunmap ä
silent! iunmap ö
```

**Comment by herverenault** [comment]
Same here for French characters î and â. I had to put this in my .vimrc
`let g:AutoPairsShortcutBackInsert=''`
`let g:AutoPairsShortcutJump=''`

**Comment by bxm** [comment]
Had a similar issue with the `§` on Mac (with English US keyboard settings FWIW); resolved with:
```
let g:AutoPairsMoveCharacter=''
```
Some other names for § — just in case anyone else is struggling to Google like me:
> section sign, section symbol, section mark, double-s, silcrow, paragraph mark, U+00A7
