### ISSUE TITLE
Swedish character å not working

### ISSUE THREAD

**Issue by robahl** [jiangmiao/auto-pairs#97]
I found out 'å' on my swedish keyboard was not working in vim. So had to disable plugin after plugin, until I found out auto-pairs was causing it. I have no idea what line in the plugin is overwriting the key.

**Comment by martinhath** [comment]
I had the same problem. See issue #88

**Comment by ggustafsson** [comment]
Just got hit by this bug :(

**Comment by AsbjornOlling** [comment]
Same issue, danish keyboard.
Strangely, the æ and ø keys are still working fine.
