### ISSUE TITLE
多括号输入方面有点问题，不利于提高效率

### ISSUE THREAD

**Issue by Svtter** [jiangmiao/auto-pairs#99]
如果存在两个`{}`这样的括号，会造成一个问题：

```c
if(condition)
{
    a = c;
    if(condition)
    {
        a = b;
    }
}
```

如果此时我删除倒数第二个`}`，那么当我再次输入的`}`的时候，会自动匹配最后一个`}`，导致

```c
if(condition)
{
    a = c;
    if(condition)
    {
        a = b;
}
```

这种情况。我不得不再次输入`}`，然后重新调整代码。

一种情况，就是如果开始代码是这样的

```c
if(condition)
{
    a = c;
    if(condition)
        a = b;
}
```

我想要将`a = b`包含在新建的`{}`内部，使得最终是这样的情况:

```c
if(condition)
{
    a = c;
    if(condition)
    {
        a = b;
    }
}
```

我也会遭遇到之前的问题。

**Comment by Svtter** [comment]
#94 也是这个问题

**Comment by jiangmiao** [comment]
我合并了 https://github.com/jiangmiao/auto-pairs/pull/89 提交
现在可以在`.vimrc`加入`let g:AutoPairsMultilineClose=0`避免多跳转。

**Comment by Svtter** [comment]
It works!  非常感谢!
